services:
  - type: web
    name: discover-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npx nx build api --configuration=production
    startCommand: node dist/apps/api/main.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
